version: '3.8'

services:
    db:
        image: 'mariadb'
        restart: always
        environment:
            MYSQL_DATABASE: blog_react
            MYSQL_ROOT_PASSWORD: root
        volumes:
           - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - '1001:80'
        environment:
            - PMA_ARBITRARY=1